### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by refriedfood** [blackcoder87/LPFM-Last.fm-Scrobbler#1] opened 2020-04-16 23:43 UTC
One issue I have though is the current version: 1.0.4.49, 07.02.2016
causes a .net error every hour or so with winamp5.666 on a windows 7x64 ultimate OS running as as a shoutcast server. I have all the visual c++ up to date.
It doesn't stop scrobbling, but it is rather annoying. Here is the details of the error:

```
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************
System.InvalidCastException: Conversion from string "C1" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at JustScrobble.Scrobbling.GetTrackInformation(String data)
   at JustScrobble.Scrobbling.StartScrobblingProcedure(String data)
   at JustScrobble.AppContext.Accept()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
JustScrobble
    Assembly Version: 1.0.4.49
    Win32 Version: 1.0.4.49
    CodeBase: file:///C:/Program%20Files%20(x86)/JustScrobble/JustScrobble.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Lpfm.LastFmScrobbler
    Assembly Version: 1.3.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/JustScrobble/Lpfm.LastFmScrobbler.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
Here is an image: https://images2.imgbox.com/dc/4a/yWggt6wH_o.png

Keep up the great work!

**Comment by blackcoder87** [comment] 2020-04-22 13:34
Thanks for reporting this bug. I am currently looking into it after setting up the development environment after years. The issue is actually not in the "LPFM-Last.fm-Scrobbler" part of JustScrobble.

I will update this issue after a version with an fix is available for download.

**Comment by blackcoder87** [comment] 2020-04-22 14:29
Please let me know if this version fixes the issue. Thanks.
https://www.blackcoder.de/downloads/JustScrobble_v1_0_5_52.rar

**Comment by refriedfood** [comment] 2020-04-22 21:53
Great! I'll install it today and report what happens.

**Comment by blackcoder87** [comment] 2020-04-26 07:55
Fixed with the above version.

**Closed as completed by blackcoder87** 2020-04-26 07:55 UTC

**Comment by refriedfood** [comment] 2020-04-29 09:52
> 
> 
> Please let me know if this version fixes the issue. Thanks.
> https://www.blackcoder.de/downloads/JustScrobble_v1_0_5_52.rar

sorry I didn't post. I tried your new version and it works great except for spanish songs with the letter ñ in the file's name. Thanks!
